### ISSUE TITLE
程序如何配置环境、训练、测试

### ISSUE THREAD

**Issue by GQM2022** [anyuzoey/CNNforFaultInterpretation#5]
您好，非常感谢您将您的程序进行分享，我想向您咨询一下，您的这一套程序的配置环境要求，和具体的运行方式，以及训练网络时训练集的基本要求，总之就是这套程序怎么用？我作为一个刚刚接触的小白，可能提出的问题比较基础，希望您能够在百忙之中抽出时间为我解答，非常感谢您。

**Comment by anyuzoey** [comment]
不知道您这边之前是否熟悉python. 我上传的程序都是用python 3.6写的 (我最近换3.8，有些包可能会稍微报错，根据错误换新的包，或者稍微调整就可以了)，GPU用的1080Ti，Cuda环境10.2。 
如果您熟悉jupyter notebook 或者google colab, 可以直接运行我的train.ipynb，可以一段段运行。这个文件里需要您修改一下数据地址。数据可以直接从readme中提到的我的论文中的链接下载。

如果您只是要使用我的模型然后测试的话，可以运行[savePredNpy_thebetest.ipynb](https://github.com/anyuzoey/CNNforFaultInterpretation/blob/master/savePredNpy_thebetest.ipynb)

希望这些能有些帮助
